name: Tunguska Mammoth
favicon: null
layout_spectrum: 0.5279260519891977
typography_spectrum: 0.4827877280768007
title: Tunguska Mammoth - Sludge Montreal
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f9f9f9'
    - '#3e3e3e'
    - '#7f7f7f'
    - '#bc4547'
    - '#070707'
  brandStrength: 0.5393076506443322
  lightness: 0.8315525222569704
  saturation: 0.8680920058395714
  rhythmicContrast: 0.8512336520943791
purpose: []
